### ISSUE TITLE
Technical Design docs

### ISSUE THREAD

**Issue by phiendp** [vydang71/infinite-integer-calculator-backend#1]
Hi Vy,

Thank you for your time working on this project. In the project requirements, we required that you should have a short write-up describing your work, code structure, any decision making you made during the call. I could not find this documentation in both of your repositories, so can you send it directly here so that I can take a look at it?

Have a nice day!

**Comment by vydang71** [comment]
Hi Phien,

Thanks for your email and reminding me. I missed it.

I wrote the backend with loopback, typescript, and MongoDB.
Initially, I wanted to set up it with the DDD (Domain Driven Design) model
(it includes application, domain, infrastructure), but it seems
time-consuming. Therefore I used the default code structure of loopback 4.
It has 4 main parts.
- Controllers: Definition of API by model. Call necessary repositories to
process API requests. Each API should solve a certain problem.
- Datasources: Setup and connect MongoDB
- Models: Define Models and their fields. Constraints and data types of
fields
- Repositories: It communicates with DB using ORM function to manipulate
the data.

*About account:*
I wrote API to signup the account. When the user uses the login API, they
will receive the token (jwt). So when I call API /accounts/{id} with id as
"me", I get information of the user who is logged in.

*About calculation: *
I want to save the user's calculation histories, so I add creatorId (FK)
for each record.
The structure of the request body:
Ex:
{
     "question": "108040000000000000100000000000000000 +
100000000000000004100000000000000000"
}

Step 1: I split this string to get an element (number, operator) (array A).
Step 2: I define object X with an index so that each operator executes the
corresponding function.
Step 3: I loop through array A and check each element against Object X. so
I can consider it a number or an operator to do proper computation.
Step 4: I've noticed that for numbers greater than 20 digits, it shows the
powers (ex: 2.7e+56). In this step, I write the function to clearly display
that number.

You can see here to review this function.
https://github.com/vydang71/infinite-integer-calculator-backend/blob/develop/src/repositories/calculation.repository.ts


*About deploy to heroku: *
I have created the release/staging branch to deploy the staging
environment. It will auto-deploy when I merge develop branch into
release/staging. I use MongoDB Atlas as the place to save data for this app.

Have experience many great things,
Vy

**Comment by vydang71** [comment]
[Additional]
About Front-end, I build the app with nextjs, reactjs, typescript, sass.

- Gateways: Through the Axios protocol to invoke API manipulation with data.
- Services: A service can contain multiple gateways to perform a certain
request.
- The "view" callback service to resolve requests
- Models: Defines the type of the model
- The position of the file in the "pages" folder identified the
application's router.
- SCSS
     + Common: shared by roles in the app (Ex: App has 2 roles such as
admin, user.)

**Comment by vydang71** [comment]
Thanks
